### ISSUE TITLE
[BUG] Strikes do not clear on restart

### ISSUE THREAD

**Issue by Firav** [PixelMindMC/PixelChatGuardian#1]
**Describe the bug**
While having the `clear-strikes-on-server-restart` config var enabled to true, the plugin fails to clear the player_strikes.yml and displays an incorrect parsing of the `cleared-strikes-on-server-restart` language var for info in console.

![firefox_2024-10-10_20-10-28](https://github.com/user-attachments/assets/57f4f0e1-f4d6-49c8-aaaf-380fbc9ce45f)

**To Reproduce**

1. Start server
2. Increase strikes of a player UUID
3. Restart server
4. Observe non-function

**Server Version**

- Minecraft Version: This server is running Paper version 1.21.1-47-master@e2da65c (2024-08-25T19:03:31Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
- Plugin Version: 1.0.0

**Additional context**
This is a fresh install with minimal changes to the configuration. DEBUG has been enabled to observe behavior of plugin.

**Comment by Gaming12846** [comment]
Thank you for reporting this problem. I have fixed it and released a new version.
